In [24]:
from __future__ import print_function
import numpy as np

ModuleNotFoundError: No module named 'pandas'

In [17]:
# Một số hàm sẽ dùng
# Hàm rand(x,y) tạo ra ma trận kích thước m*n, các phần tử là random trong (0,1] trên phân phối đều (uniformDis)
X = np.random.rand(3, 2) 
print("Ma tran X: ", X)
size = X.shape  # .shape trả về property shape là một tuple m*n: (m, n)
print("Kích thước ma trận X: ", size)
# Hàm np.zeros_like(X) trả về ma trận giống X nhưng toàn là 0
zeros_X = np.zeros_like(X)
print("Ma trận X với 0: ", zeros_X)
# Hàm đối tượng .reshape(-1) của ndarray làm phẳng ma trận
X_flat = X.reshape(-1)
print("X làm phẳng: ", X_flat)
# Hàm đối tượng .reshape((a,b)) cố gắng chuyển ma trận cũ thành kích thước a*b
X = X_flat.reshape((2,3))
print("Chuyển X về 2*3", X)


Ma tran X:  [[0.93830579 0.2318229 ]
 [0.57123808 0.17671346]
 [0.61109458 0.16188707]]
Kích thước ma trận X:  (3, 2)
Ma trận X với 0:  [[0. 0.]
 [0. 0.]
 [0. 0.]]
X làm phẳng:  [0.93830579 0.2318229  0.57123808 0.17671346 0.61109458 0.16188707]
Chuyển X về 2*3 [[0.93830579 0.2318229  0.57123808]
 [0.17671346 0.61109458 0.16188707]]


In [19]:
# Đoạn code sau kiểm tra đạo hàm của hàm khả vi f: R(mxn) -> R có kèm theo hai ví dụ

def check_grad(fn, gr, X):
    X_flat = X.reshape(-1)  # truyền -1 để chuyển đổi X thành array 1d => cần 1 for loop
    shape_X = X.shape       # hình dạng gốc của X
    # Khởi tạo ma trận num_grad có cùng hình dạng như X với tất cả các phần tử 
    # được đặt bằng 0. Ma trận này sẽ chứa gradient tính toán.
    num_grad = np.zeros_like(X)     
    # như lệnh trên nhưng dùng cho X đã flatten
    grad_flat = np.zeros_like(X_flat)   
    eps = 1e-6      # epsilon, chọn 1e-10 -> 1e-6 thường tốt
    numElems = X_flat.shape[0]      # số phần tử trong X, ma trận m * n  thì shape[0] = m

    # Tính đạo hàm theo numerical
    # For loop qua các phần tử trong X
    for i in range(numElems):
        Xp_flat = X_flat.copy()
        Xn_flat = X_flat.copy()
        Xp_flat[i] += eps
        Xn_flat[i] -= eps
        Xp = Xp_flat.reshape(shape_X)
        Xn = Xn_flat.reshape(shape_X)
        grad_flat[i] = (fn(Xp) - fn(Xn)) / (2*eps)     # Tính đạo hàm theo numerical
    
    num_grad = grad_flat.reshape(shape_X)
    print("Num_grad: ", num_grad)
    print("Gr(x) = ", gr(X))
    print("Hieu: ", num_grad - gr(X))
    diff = np.linalg.norm(num_grad - gr(X)) # tính sai khác bằng chuẩn Euclide

    print("Difference between two methods should be small: ", diff)

# === Kiểm ra xem grad(trace(A*X) == A^T) ===
m, n = 3, 4
A = np.random.rand(m, n)    # trả về list (ma trận) m * n với các số random [0, 1)
X = np.random.rand(n, m)

def fn1(X):
    return np.trace(A.dot(X))
def gr1(X):
    return A.T
check_grad(fn1, gr1, X)

# === Kiểm tra xem grad(x^T*A*x) == (A + A^T)*x
A = np.random.rand(m, m)
x = np.random.rand(m, 1)

def fn2(x):
    return x.T.dot(A).dot(x)
def gr2(x):
    return (A + A.T).dot(x)
check_grad(fn2, gr2, x)


Num_grad:  [[0.81542667 0.74452236 0.1146039 ]
 [0.58106663 0.73554514 0.12444742]
 [0.22326838 0.48301633 0.99415231]
 [0.09553278 0.60886831 0.78108107]]
Gr(x) =  [[0.81542667 0.74452236 0.1146039 ]
 [0.58106663 0.73554514 0.12444742]
 [0.22326838 0.48301633 0.99415231]
 [0.09553278 0.60886831 0.78108107]]
Hieu:  [[-6.61133370e-11 -2.00202077e-11  1.38082878e-11]
 [ 1.23677402e-10 -2.24651409e-11 -2.12770357e-10]
 [-6.09297057e-11 -5.64027713e-11 -2.11058948e-11]
 [ 1.92789562e-10 -2.19029239e-11 -8.84198270e-11]]
Difference between two methods should be small:  3.4473067379501283e-10
Num_grad:  [[2.21622454]
 [2.69267436]
 [0.56124278]]
Gr(x) =  [[2.21622454]
 [2.69267436]
 [0.56124278]]
Hieu:  [[-6.64819311e-11]
 [ 4.60342875e-11]
 [ 2.70644618e-11]]
Difference between two methods should be small:  8.527301962266641e-11


C:\Users\DELL\AppData\Local\Temp\ipykernel_19276\326430466.py:23: DeprecationWarning: Conversion of an array with ndim > 0 to a scalar is deprecated, and will error in future. Ensure you extract a single element from your array before performing this operation. (Deprecated NumPy 1.25.)
  grad_flat[i] = (fn(Xp) - fn(Xn)) / (2*eps)     # Tính đạo hàm theo numerical


In [23]:
A = np.array([[1,2,3],[2,3,1]])
A
np.linalg.norm(A)

5.291502622129181